/**
 * Wealth Series VSL — Slide Text Data (V11 — $500 Refundable Deposit + RIA Partner Model)
 *
 * Each entry: [slideNumber, spokenText, silenceDurationSec]
 *   - text=null means silence-only slide
 *   - silenceSec=0 means duration is determined by speech length
 *   - <break time="Xms"/> markers indicate pauses (handled by audio pipeline)
 *
 * Text is sent through normalizeForTTS() before TTS generation.
 *
 * POSITIONING: TradeAlgo = AI analytics company that builds AI signal-generation systems.
 * A licensed RIA partner manages portfolios and executes trades based on AI signals.
 * Client capital held at institutional custodian. TradeAlgo never touches money.
 *
 * BANNED: securities, fiduciary, qualified custodian, SEC, regulated, compliance,
 *         three-entity structure.
 *
 * CTA: Apply -> $500 fully refundable deposit -> private strategy session.
 * Q2 2026 founding cohort. 200-member cap per tier.
 */

export const SLIDES = [
  // ── SCENE 1: Hook / Pattern Interrupt — INTRIGUE (0:00-0:30) ──
  [1, null, 3],
  [2, null, 5],
  [3, `Fifty-two point eight percent. <break time="600ms"/> In one year. <break time="400ms"/> Not a backtest. Not a simulation. Not a projection.`, 0],
  [4, `This is what an AI, a real AI, not a marketing gimmick, produced across 86 stocks and 15 sectors over the last twelve months. Every signal published. Every trade documented.`, 0],
  [5, `In the next twenty minutes, I'm going to show you something that changed how I think about markets. And I think it might change how you think about them, too. <break time="500ms"/> But first, you need to understand the problem this AI was built to solve.`, 0],

  // ── SCENE 2: The Problem — Complexity is the Villain (0:30-2:00) ──
  [6, `Here's something most people don't fully appreciate. <break time="300ms"/> Every single week, the US equity markets generate an extraordinary amount of data. Earnings reports. Macro releases. Sector rotations. Technical indicators crossing thresholds. Institutional capital flowing between sectors. <break time="400ms"/> The sheer volume is staggering.`, 0],
  [7, `Imagine trying to read 86 different research reports, in 15 different sectors, evaluating momentum, relative strength, macro conditions, and institutional flow, and then making a decision about every single position, before Monday's opening bell. <break time="500ms"/> Now imagine doing that every week. Fifty-two weeks a year. Without missing one.`, 0],
  [8, `It's not possible. Not for one person. Not for a team of ten. The data moves too fast, across too many stocks, with too many interdependencies. <break time="300ms"/> This isn't a criticism of human intelligence. It's a recognition of a simple truth: modern markets have outgrown what any human can consistently process.`, 0],
  [9, `And that gap, between the volume of data the market produces and what any human can analyze, that gap is where opportunity lives. And where risk hides.`, 0],
  [10, `And that's where something remarkable happened. <break time="600ms"/> But to understand why it's remarkable, you need to understand the scale of what this AI actually does.`, 0],

  // ── SCENE 3: Origin Story — CURIOSITY -> FASCINATION (2:00-4:00) ──
  [11, `Three years ago, a team of engineers and data scientists asked a deceptively simple question.`, 0],
  [12, `What if an AI could evaluate every stock in a diversified portfolio, across every sector, analyze dozens of technical and fundamental indicators, generate actionable trading signals, and then explain its reasoning, in writing, for every single decision? <break time="500ms"/> Not a black box. Not trust the algorithm. An AI that shows its work. Like an institutional analyst writing a research note, except it does it for 86 stocks. Every week. Without fail.`, 0],
  [13, `So they built it. An AI system that evaluates 86 stocks across 15 sectors. It analyzes RSI. CCI. Momentum indicators. Institutional flow. Macro conditions. Sector rotation patterns. And it generates rebalancing signals, adding, trimming, or exiting positions based on the data.`, 0],
  [14, `52 signal cycles per year. Every week, without exception. No vacations. No emotional reactions. No recency bias. No fatigue. <break time="600ms"/> But here's what happened next that nobody expected.`, 0],
  [15, `When they first ran the AI on live market data, tracking real portfolios, the team thought there was an error. <break time="400ms"/> The numbers were too good. They ran the analysis again. Same result. They checked the data inputs. They audited the trade log. Everything checked out. <break time="400ms"/> The AI wasn't just generating signals. It was generating signals that, when acted on, produced returns they hadn't anticipated.`, 0],
  [16, `And here's the part that made them realize this was different from anything else in the market. The AI wasn't just making decisions. It was explaining its decisions. In writing. For every single position. <break time="1500ms"/> I'm going to show you exactly what that looks like. The track record. The reasoning. The structure. All of it. <break time="3000ms"/>`, 0],

  // ── SCENE 4: The Reveal / Transition — FASCINATION (4:00-5:00) ──
  [17, null, 3],
  [18, `Imagine having a room of 50 Wall Street analysts, each one an expert in their sector, working through the night every Sunday. And by Monday morning, they hand you a single page. Here's what to own. Here's what to sell. And here's exactly why. <break time="500ms"/> That's what this AI does. Except it doesn't take a team of 50. It does it alone. Every week. And it writes the reasoning for every decision.`, 0],
  [19, `An AI analyzing 86 stocks across 15 sectors, with a signal track record you can verify yourself. <break time="300ms"/> Not a robo-advisor allocating to 6 ETFs. Not a chatbot picking stocks. <break time="300ms"/> A complete AI signal platform, with a documented track record you can verify, available to qualified investors through a selective enrollment process.`, 0],
  [20, `Let me show you exactly what this looks like. And I'll start with the part that changed my mind about AI investing forever. <break time="500ms"/>`, 0],

  // ── SCENE 5: The Solution Reveal — FASCINATION (5:00-8:00) ──
  [21, `The Wealth Series is a collection of 11 portfolios, powered by TradeAlgo's AI-generated trading signals, with every signal published weekly and fully documented.`, 0],
  [22, `And before I show you the numbers, let me be clear about how this works. Because the model is what makes this trustworthy. <break time="400ms"/> TradeAlgo is an AI analytics company. They build the AI and generate trading signals. Every week, you receive the signals, the analysis, and full reasoning notes, and you decide how to act. <break time="300ms"/> TradeAlgo never touches your money. They generate the signals. You read the reasoning. You make the call. And if you prefer hands-free? An RIA partner can execute the signals automatically in a managed account. But that's optional, you're always in control.`, 0],
  [23, `The AI analyzes 86 unique stocks across 15 sectors. Healthcare. Technology. Industrials. Consumer defensive. Basic materials. Real estate. Energy. And more.`, 0],
  [24, `Every week, the AI evaluates every position. It scores each stock using RSI, CCI, momentum indicators, sector rotation analysis, and macro conditions. It then generates rebalancing signals, adding, trimming, or exiting positions based on the data.`, 0],
  [25, `And here's what makes this unlike anything else. <break time="400ms"/> The AI writes its reasoning. For every single signal. In plain English. <break time="300ms"/> You can read exactly why it recommended buying, selling, or holding every position. It's like having a chief analyst who writes you a detailed memo, every week, for every holding in the portfolio.`, 0],
  [26, `11 portfolios across 3 tiers. Each tier offers high-growth, balanced, and defensive options. You choose the risk level. The AI generates the signals with full reasoning notes. You decide how to act.`, 0],
  [27, `11 portfolios. 86 stocks. 15 sectors. 52-plus signal cycles per year. Every signal published with institutional-grade reasoning. Every trade documented.`, 0],
  [28, `This isn't a black box. It's the most transparent AI signal platform available to individual investors. <break time="500ms"/> Now let me show you the numbers. And I'll start with the one that made me do a double-take.`, 0],

  // ── SCENE 6: Proof / Track Record — BELIEF (8:00-12:00) ──
  [29, `Before I show you performance data, the standard disclosure: past performance is not indicative of future results, and all investing involves risk, including loss of principal. That disclaimer will remain on screen. <break time="500ms"/> Now, the actual numbers.`, 0],
  [30, `These are real portfolios, guided by AI signals, with every trade documented and timestamped. <break time="400ms"/> Plus 52.8 percent, Everest Momentum Ascent. <break time="300ms"/> Plus 45.5, Titan Dynamic Upside. <break time="300ms"/> Plus 43.9, Atlas Accelerated Growth.`, 0],
  [31, `And here's the one that stops people. Capital Shield. <break time="300ms"/> This is the defensive portfolio. Designed for capital preservation. Not aggressive growth. Low risk. <break time="400ms"/> It returned 27 percent in a year. <break time="1500ms"/> When I first saw that number, 27 percent from a defensive strategy, I had to double-check. A defensive portfolio isn't supposed to return 27 percent. But when I looked at the AI's reasoning notes, it made sense. The AI had been rotating into defensive sectors, consumer staples, utilities, gold, that happened to outperform during a volatile year. It wasn't luck. It was data-driven positioning.`, 0],
  [32, `Now let me show you the thing that changed how I think about AI investing. Because the returns are impressive, but the reasoning is what separates this from everything else.`, 0],
  [33, `This is the AI's actual reasoning for a recent rebalance. <break time="300ms"/> It writes: IAUM is nearing overbought territory with an RSI of 69.69 and CCI of 161.34, suggesting strong buying pressure but a potential for short-term consolidation. <break time="300ms"/> So it trimmed the gold position by 1.1 percent. Not based on a feeling. Not based on a headline. Based on quantitative analysis, explained in writing, available for anyone to read and verify.`, 0],
  [34, `This isn't a black box that says trust us. It shows its work. Every week. For every position. In language an institutional analyst would recognize. <break time="500ms"/> Every signal is documented. Every reasoning note is archived. You can verify every decision the AI made.`, 0],
  [35, `Now, performance is one thing. But what about when markets drop? <break time="500ms"/> Remember February? Markets pulled back. Financial news was filled with concern. But here's what was already in the portfolio two weeks before the drop: short S&P 500 positions in 8 of 11 portfolios. An active hedge, a position that gains value when the market falls.`, 0],
  [36, `The AI didn't react to the February pullback. It had already positioned for it. Gold at 5 percent across every portfolio. Consumer staples, US Foods, Anheuser-Busch, Philip Morris, in every portfolio regardless of risk level. Short S&P hedge in 8 of 11 portfolios. <break time="300ms"/> Three layers of defense, all in place before anyone knew the pullback was coming.`, 0],
  [37, `Result? Portfolios drew down 2 to 3.7 percent during the pullback. The hedges absorbed the impact. <break time="400ms"/> The AI didn't panic. It didn't react. <break time="300ms"/> It had anticipated.`, 0],
  [38, `86 unique stocks. 15 sectors. 55 rebalancing events documented in the last 5 weeks alone. 26 to 68 tickers adjusted per rebalance.`, 0],
  [39, `Here's the reality, a team of 10 human analysts couldn't process this volume of data, across this many sectors, with this consistency, week after week. The AI does it every 7 days, and writes the reasoning for every single signal it generates.`, 0],
  [40, `This is not a stock screener. This is not a robo-advisor buying 6 ETFs. <break time="300ms"/> This is institutional-grade AI portfolio management, the kind of technology that family offices pay millions to access, now available to qualified individual investors through our selective enrollment process.`, 0],
  [41, `So how do you actually access this? <break time="400ms"/> It's simpler than you'd expect.`, 0],

  // ── SCENE 7: How It Works — DESIRE (12:00-14:00) ──
  [42, `Here's how it works. 3 steps. <break time="300ms"/> Step one: you apply. We review every application personally to ensure the right fit. It takes 2 minutes. No cost, no obligation.`, 0],
  [43, `Step two: if you qualify, you place a fully refundable five-hundred-dollar deposit to secure your private strategy session. That deposit applies in full toward your membership if you proceed, or you get every penny back if you don't. <break time="400ms"/> Zero risk. The deposit simply reserves your consultation and ensures we're speaking with serious investors.`, 0],
  [44, `Step three: a 30-minute private strategy session. We walk through the AI system, review recent signals, and discuss whether this is the right fit for your portfolio.`, 0],
  [45, `This is what your dashboard looks like. Every position. Every weight. Every AI reasoning note. Updated every week. Complete transparency.`, 0],
  [46, `The AI generates signals. You read the reasoning. You decide how to act. <break time="500ms"/> That's the system. No complexity. No guesswork. Just data-driven AI signals, full transparency, and you in control. Optional: have an RIA partner execute the signals automatically.`, 0],

  // ── SCENE 8: The Three Tiers — DESIRE (14:00-16:00) ──
  [47, `So at this point, you've seen exactly what this AI does. You've seen the signals. You've seen the returns. And I know what you're thinking: what does something like this cost? <break time="400ms"/> Let me put this in perspective. If you wanted to build an AI system like this from scratch, you'd need machine learning engineers, that's $200,000 a year, minimum. Institutional-grade data feeds, another $30,000 to $50,000 a year. Cloud computing for the models? $50,000 a year. TradeAlgo raised over one hundred million dollars in capital, with one prime directive: building the most powerful AI trading system ever created. Three years of intensive development went into what you're looking at right now. <break time="400ms"/> A single Bloomberg Terminal costs $32,000 per year, and it gives you data alone. No signals. No reasoning notes. This AI does all of that. The technology behind this system represents over one hundred million dollars in investment. And for the first time, it's available to qualified individual investors.`, 0],
  [48, `Atlas gives you access to 3 AI-driven signal portfolios, each calibrated to a different risk level. High growth, balanced, and defensive. The AI generates signals across up to 31 holdings, with full reasoning notes every week. <break time="300ms"/> Weekly AI rebalancing. Full reasoning documentation. 3 risk levels to match your investment approach.`, 0],
  [49, `Titan expands the portfolio to 40 holdings, broader diversification, deeper sector coverage, and the AI's full analytical arsenal. Dynamic Upside returned 45.5 percent. <break time="300ms"/> This is for the serious investor who wants expanded coverage and the kind of analysis that most institutional desks would pay millions to access.`, 0],
  [50, `Everest is the flagship. 5 portfolios. Up to 51 holdings. Maximum diversification. And access to the AI's most sophisticated signal set. <break time="300ms"/> Momentum Ascent, the top performer at plus 52.8 percent, is an Everest-exclusive portfolio. This is the AI's most sophisticated signal set. The deepest diversification. The broadest sector coverage.`, 0],
  [51, `Now, here's what makes this even better. Founding members lock in their rate permanently. As the AI improves, as we add new models, as the track record lengthens, founding member pricing never increases. Current pricing reflects founding member rates. As the AI's track record grows, pricing increases to reflect proven performance. But founding members are locked in at today's rate, permanently. <break time="400ms"/> 3 years also matters for another reason. Compounding. This system is designed to build wealth over time. The AI's signals need time to navigate full market cycles, earnings seasons, Fed decisions, corrections, and rallies. A 3-year window is how institutional investors think, and it's why the results compound. <break time="300ms"/> The Q2 2026 founding cohort is now accepting applications.`, 0],

  // ── SCENE 9: Objection Handling — CONVICTION (16:00-19:00) ──
  [52, `Now, I know what you're thinking. Let me address it head-on. <break time="400ms"/> What about market crashes? <break time="400ms"/> Fair question. Let me show you what the AI is doing right now. It's holding short S&P 500 positions in 8 of 11 portfolios. It has a 5 percent gold allocation across every portfolio. It maintains a defensive core, consumer staples, utilities, healthcare, in every portfolio regardless of risk level. <break time="300ms"/> Last month, the market pulled back. The AI's portfolios drew down 2 to 3.7 percent. The hedges were already in place. The AI doesn't react to crashes, it positions for them in advance.`, 0],
  [53, `Is this a significant investment? <break time="400ms"/> Yes. This is institutional-grade AI, the kind of technology that drives the most sophisticated strategies on Wall Street. We're selective about who we work with because performance matters. <break time="300ms"/> The system analyzes 86 stocks across 15 sectors every week and generates documented signals with full reasoning notes. The top portfolio returned plus 52.8 percent in its first year. Your strategy call will cover exactly how the investment works for your specific portfolio size.`, 0],
  [54, `Is AI safe for investing? <break time="400ms"/> TradeAlgo builds the AI that generates the signals. You can act on them yourself, or optionally have an RIA partner manage execution. Either way, TradeAlgo never touches your money. <break time="300ms"/> And the AI's reasoning is documented and transparent, you can read exactly why it generated every signal. This is the most transparent AI signal platform available to individual investors.`, 0],
  [55, `Why not just buy index funds? <break time="400ms"/> You can. And the low-volatility portfolios actually include index fund ETFs as a core holding. But here's what passive index exposure alone doesn't provide. <break time="300ms"/> Active risk management. Weekly sector rotation based on data. Position trimming when technical indicators signal overbought conditions. Short positions as hedges before pullbacks. <break time="300ms"/> An index fund held through a 20 percent drawdown is a 20 percent loss. AI-driven signal portfolios with active risk management is a fundamentally different approach.`, 0],
  [56, `How is this different from Wealthfront or Betterment? <break time="400ms"/> Robo-advisors allocate your money across 6 to 12 ETFs based on a risk questionnaire. Then they rebalance when your allocation drifts. That's it. <break time="300ms"/> The Wealth Series AI generates signals across 86 individual stocks. It drives weekly rebalancing. It uses RSI, CCI, momentum, sector rotation, and macro analysis. It writes institutional-grade reasoning for every signal, and you see all of it. <break time="300ms"/> And its top portfolio returned plus 52.8 percent in a year. And unlike institutional platforms that require five million dollar minimums, the Wealth Series is accessible to qualified investors. These are fundamentally different products.`, 0],
  [57, `Why 3 years? <break time="400ms"/> Two reasons. First, founding members lock in their rate. As the AI improves and the track record lengthens, pricing increases. But your rate never changes. <break time="300ms"/> Second, compounding. AI-driven strategies work over full market cycles, not weeks. Last month, high-risk portfolios drew down 3 to 4 percent. Over a year, those same portfolios returned 43 to 52 percent. 3 years also gives us time to demonstrate the AI's full capability across complete market cycles, bull markets, corrections, and everything in between.`, 0],

  // ── SCENE 10: Authority — CONVICTION (19:00-21:00) ──
  [58, `Let me tell you who's behind this, because the technology only matters if you trust the infrastructure around it.`, 0],
  [59, `TradeAlgo built the AI. They're an AI analytics company, not a brokerage, not a fund. Their job is building and refining the AI signal-generation algorithms. You receive the signals and reasoning notes. You decide how to act. TradeAlgo never touches your money.`, 0],
  [60, `TradeAlgo is an AI analytics company that generates trading signals across 86 stocks and 15 sectors, the kind of analysis that hedge funds and family offices have relied on for decades, now available to individual investors. <break time="400ms"/> You receive the signals. You read the reasoning. You decide how to act. TradeAlgo never touches your money. Optional: an RIA partner can execute the signals automatically in a managed account.`, 0],
  [61, `One AI system. A documented track record. Complete transparency. And a managed portfolio model that keeps your capital exactly where it belongs, at the institutional custodian.`, 0],
  [62, `And the track record isn't a pitch deck with cherry-picked numbers. It's 55 documented rebalancing events. Every trade timestamped. Every AI reasoning note archived. This is the most auditable AI-driven portfolio system available to individual investors. <break time="400ms"/> You don't have to take our word for it. You can verify every single trade yourself.`, 0],

  // ── SCENE 11: Urgency — CONVICTION -> ACTION (21:00-22:00) ──
  [63, `The AI runs continuously. While we've been talking, it's been evaluating positions, scoring stocks, and generating signals for the next cycle.`, 0],
  [64, `Every week, the system generates a new cycle of documented decisions across 86 stocks. The track record grows. The AI improves. And founding member pricing won't last indefinitely.`, 0],
  [65, `We cap each tier at 200 founding members, this is a genuine constraint, not a marketing tactic. The AI's edge depends on signal exclusivity. When too many investors follow identical signals, alpha decays, the edge erodes. <break time="500ms"/> The Q2 2026 founding cohort has limited spots remaining. Submit your application, and we'll review it personally.`, 0],

  // ── SCENE 12: The Close / CTA — ACTION (22:00-24:00) ──
  [66, `Let me bring it together.`, 0],
  [67, `You've seen 11 portfolios powered by AI-generated signals. Returns of up to 52.8 percent in a year. Institutional-grade reasoning for every position, every week. Risk management, hedges, gold, defensive positioning built into every portfolio. <break time="400ms"/> And you've seen the model: an AI analytics company generating the signals. Full transparency. You decide how to act.`, 0],
  [68, `The next step is simple. Click below to submit your application. It takes 2 minutes, no cost, no obligation. If you qualify, we'll invite you to place a fully refundable five-hundred-dollar deposit to secure your private strategy session. That deposit applies in full toward your membership if you proceed, or you get every penny back if you don't. No risk.`, 0],
  [69, `The system is running. The signals are being generated. The five-hundred-dollar deposit is fully refundable within 14 days if you decide not to proceed. It simply reserves your consultation and ensures we're speaking with serious investors.`, 0],
  [70, `Click below to apply. If you qualify, a refundable five-hundred-dollar deposit secures your consultation. We'll walk through the AI system, review recent performance, and discuss whether this is the right fit for your portfolio. The deposit is fully refundable. The application is free. Zero risk to explore. <break time="30000ms"/>`, 0],
  [71, null, 5],
];
